project:
  name: fertility_popEVE
  version: 0.1.0

paths:
  reference: /home/tian/ngs_project/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
  bed: /home/tian/ngs_project/bed/exons.bed

  raw_gvcf: data/raw_gvcf
  raw_gvcf_test: data/raw_gvcf_test

  joint_test: data/joint_test
  joint_vcf: data/joint_vcf

  annotation: data/annotation
  missense: data/missense
  protein: data/protein
  features: data/features
  embedding: data/embedding
  gp: data/gp

  reference_data: data/reference

  logs: logs
  outputs: outputs

gatk:
  threads: 4

vep:
  cache: ~/.vep
  assembly: GRCh38
  fork: 4

esm:
  model: esm1v

files:
  protein_mapping: data/reference/mapping/protein_mapping.parquet
  mapping_cache: data/reference/cache/ensembl_mapping.json

models:
  popeve: models/popEVE/data
